### ISSUE TITLE
Voucher management changes

### ISSUE THREAD

**Issue by ramlaxmi** [seyyonist/seyon-ui#13]
Following is the fields we need to have - 
Voucher number
Voucher date
Invoice No
Invoice Date
Vendor Name
Vendor address
Vendor GST
Vendor bank details(Acctno,bacnk name, branch)
Vendor PAN
Head of account
AMount gross
CGST
SGST
IGST
Net amount
TDS section
TDS%
Net payable
Description / Narration

**Comment by ramlaxmi** [comment]
Add edit functionality in search page

**Comment by ramlaxmi** [comment]
in progress

**Comment by nvijaykarthik** [comment]
Done
